""" Task 1"""

SOME_STR_IS = 'e1i2am4some4str'
FIRST_SYMBOL = SOME_STR_IS[0]
LAST_SYMBOL = SOME_STR_IS[-1]
THIRD_SYMBOL = SOME_STR_IS[2]
LAST_THREE_SYMBOL = SOME_STR_IS[-3]
LEN_STR = len(SOME_STR_IS)
REVERSE_STR = SOME_STR_IS[::-1]
FIRST_SYMBOLS = SOME_STR_IS[0:8]
